#!/bin/bash

# Bison Pulse - Sanitization Check Script
# Run this script to check for forbidden terms before committing

echo "🔍 Running sanitization check..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Forbidden terms (case-insensitive)
FORBIDDEN_TERMS=("lovable" "ai builder" "generated by" "lovable-dev" "lovable-dev[bot]")

# Check file contents
echo "Checking file contents..."
for term in "${FORBIDDEN_TERMS[@]}"; do
    if grep -r -i "$term" --exclude-dir=.git --exclude="*.yml" --exclude="*.yaml" --exclude="check-sanitization.sh" . > /dev/null 2>&1; then
        echo -e "${RED}❌ Found forbidden term: '$term'${NC}"
        grep -r -i "$term" --exclude-dir=.git --exclude="*.yml" --exclude="*.yaml" --exclude="check-sanitization.sh" .
        exit 1
    fi
done

# Check file names
echo "Checking file names..."
for term in "${FORBIDDEN_TERMS[@]}"; do
    if find . -name "*$term*" | grep -v ".git" > /dev/null 2>&1; then
        echo -e "${RED}❌ Found forbidden term in file name: '$term'${NC}"
        find . -name "*$term*" | grep -v ".git"
        exit 1
    fi
done

# Check package.json
echo "Checking package.json..."
if grep -i "lovable" package.json > /dev/null 2>&1; then
    echo -e "${RED}❌ package.json contains forbidden dependencies${NC}"
    exit 1
fi

# Check README
echo "Checking README..."
if grep -i "lovable\|ai builder\|generated by" README.md > /dev/null 2>&1; then
    echo -e "${RED}❌ README contains vendor attribution${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Sanitization check passed!${NC}"
echo -e "${YELLOW}💡 Remember to use 'Bison Pulse' as the product name and 'system' as the neutral fallback.${NC}"
